// leave off @2x/@3x
const images = {
  logo: require('../Images/roust_logo.png'),
  clearLogo: require('../Images/hz.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  login_bg: require('../Images/login_bg.png'),
  sell: require('../Images/sell.png'),
  buy: require('../Images/buy.png'),
  tag: require('../Images/tag.png'),
  rupee: require('../Images/rupee.png'),
  check: require('../Images/check.png'),
  cart: require('../Images/cart.png'),
  basket: require('../Images/basket.png'),
  tilttag: require('../Images/tilttag.png'),
  chats: require('../Images/chats.png'),
  gifbg: require('../Images/gifbg.gif')
}

export default images
